name: Action Get Merged Pull Request
description: Get the pull request merged with base branch.
author: kogangdon
inputs:
  github_token:
    description: A GitHub token.
    required: true
outputs:
  title:
    description: The title of the pull request.
  body:
    description: The body of the pull request.
  number:
    description: The number of the pull request.
  labels:
    description: The list of labels for the pull request. Separated with line breaks if there're multiple labels.
  assignees:
    description: The list of assignees for the pull request. Separated with line breaks if there're multiple assignees.
  merged_by:
    description: The user who merged the pull request.
runs:
  using: node20
  main: dist/index.js
